ASoC: codecs: aw88261: small cleanup in aw88261_set_tdm_slot()
This code triggers a Smatch false positive:

    sound/soc/codecs/aw88261.c:858 aw88261_set_tdm_slot()
    error: uninitialized symbol 'chan'.

This would only happen if both the tx and rx masks were zero which is
a nonsense scenario and reviewing the callers shows that it never
happens.

However, if the rx_mask is zero then we're comparing the mask from RX
against the chan from TX which is confusing:

	if ((rx_mask & ~BIT(chan)) != 0) {
             ^^ rx          ^^^^ tx chan

Of course, in that case the condition is going to be false because
the rx_mask is zero.  So it's fine.  But it would be more clear to move
the condition inside the if statement and it silences the static checker
warning as well.

Signed-off-by: Dan Carpenter <error27@gmail.com>
Link: https://patch.msgid.link/ar4C-0NIYXiAvxvv@stanley.mountain
Signed-off-by: Mark Brown <broonie@kernel.org>