phy: qcom: qmp-pcie: drop unused reset names
Commit e397c8507e36 ("phy: qcom: qmp-pcie: Add Nord Gen5x16 PCIe
multi-PHY support") added a bunch of reset names, but also added two
which are not being used.

This leads to compiler warnings:
drivers/phy/qualcomm/phy-qcom-qmp-pcie-multiphy.c:750:27: error: ‘nord_pciephy_port_b_nocsr_reset_l’ defined but not used [-Werror=unused-const-variable=]
  750 | static const char * const nord_pciephy_port_b_nocsr_reset_l[] = {
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/phy/qualcomm/phy-qcom-qmp-pcie-multiphy.c:746:27: error: ‘nord_pciephy_port_a_nocsr_reset_l’ defined but not used [-Werror=unused-const-variable=]
  746 | static const char * const nord_pciephy_port_a_nocsr_reset_l[] = {
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Drop these

Fixes: e397c8507e36 ("phy: qcom: qmp-pcie: Add Nord Gen5x16 PCIe multi-PHY support")
Signed-off-by: Vinod Koul <vkoul@kernel.org>